// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5uWuKePOWO52ZhQ4u0wnz49MeJaj6G6M',
    appId: '1:400942120127:android:1c121e12c26274913f5a0a',
    messagingSenderId: '400942120127',
    projectId: 'optifoodflutter-3f03a',
    databaseURL: 'https://optifoodflutter-3f03a-default-rtdb.firebaseio.com',
    storageBucket: 'optifoodflutter-3f03a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkcWgyGhZ3_cbrYzrAnQTyIOrgyiNvQXE',
    appId: '1:400942120127:ios:e460e3bba9a9cd473f5a0a',
    messagingSenderId: '400942120127',
    projectId: 'optifoodflutter-3f03a',
    databaseURL: 'https://optifoodflutter-3f03a-default-rtdb.firebaseio.com',
    storageBucket: 'optifoodflutter-3f03a.appspot.com',
    iosBundleId: 'com.medcoanalytics.erxethiopia',
  );
}
